# Generated by Django 5.2.14 on 2026-05-09 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('tel', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('interes', models.CharField(blank=True, max_length=300, verbose_name='Interés principal')),
                ('source', models.CharField(choices=[('web', 'Sitio web'), ('ig', 'Instagram'), ('fb', 'Facebook'), ('wa', 'WhatsApp'), ('ref', 'Referido'), ('evento', 'Evento')], default='web', max_length=20, verbose_name='Origen')),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('interested', 'Interesado'), ('contacted', 'Contactado'), ('registered', 'Registrado a taller'), ('client', 'Cliente'), ('recurring', 'Cliente recurrente'), ('potential_biz', 'Empresa potencial'), ('discarded', 'Descartado')], default='new', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas comerciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contacts.contact', verbose_name='Contacto')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
