# Generated by Django 5.2.14 on 2026-05-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('tel', models.CharField(max_length=30, verbose_name='Teléfono / WhatsApp')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa / Proyecto')),
                ('appointment_type', models.CharField(choices=[('asesoria_ia', 'Asesoría IA'), ('diagnostico', 'Diagnóstico de negocio'), ('automatizacion', 'Automatización'), ('desarrollo', 'Desarrollo de software'), ('capacitacion', 'Capacitación empresarial'), ('mentoria', 'Mentoría personalizada')], default='diagnostico', max_length=30, verbose_name='Tipo de cita')),
                ('notas', models.TextField(blank=True, verbose_name='¿Qué quieres lograr?')),
                ('status', models.CharField(choices=[('requested', 'Solicitada'), ('confirmed', 'Confirmada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada')], default='requested', max_length=20, verbose_name='Estado')),
                ('source', models.CharField(choices=[('web', 'Sitio web'), ('ig', 'Instagram'), ('fb', 'Facebook'), ('wa', 'WhatsApp'), ('ref', 'Referido'), ('evento', 'Evento')], default='web', max_length=20, verbose_name='Origen')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-created_at'],
            },
        ),
    ]
