# Generated by Django 5.2.14 on 2026-05-09 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('tel', models.CharField(max_length=30, verbose_name='WhatsApp / Teléfono')),
                ('ocupacion', models.CharField(blank=True, max_length=200, verbose_name='Ocupación')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('fuente', models.CharField(choices=[('web', 'Sitio web'), ('ig', 'Instagram'), ('fb', 'Facebook'), ('wa', 'WhatsApp'), ('ref', 'Referido'), ('evento', 'Evento')], default='web', max_length=20, verbose_name='¿Cómo nos conociste?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de pago'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado de asistencia')),
                ('payment_status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado de pago')),
                ('payment_method', models.CharField(choices=[('transferencia', 'Transferencia SPEI'), ('tarjeta', 'Tarjeta crédito/débito'), ('oxxo', 'OXXO Pay'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo')], default='transferencia', max_length=20, verbose_name='Método de pago')),
                ('folio', models.CharField(max_length=30, unique=True, verbose_name='Folio')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('attended', models.BooleanField(default=False, verbose_name='Asistió')),
                ('check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Hora de check-in')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='registrations.attendee', verbose_name='Asistente')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='workshops.workshop', verbose_name='Taller')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-registered_at'],
                'unique_together': {('attendee', 'workshop')},
            },
        ),
    ]
