# Generated by Django 5.2.14 on 2026-05-09 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('client_sector', models.CharField(max_length=200, verbose_name='Cliente / Sector')),
                ('problem', models.TextField(verbose_name='Problema inicial')),
                ('solution', models.TextField(verbose_name='Solución aplicada')),
                ('result', models.TextField(verbose_name='Resultado obtenido')),
                ('testimonial', models.TextField(blank=True, verbose_name='Testimonio')),
                ('category', models.CharField(choices=[('small_biz', 'Negocios pequeños'), ('photographers', 'Fotógrafos'), ('lawyers', 'Abogados'), ('restaurants', 'Restaurantes'), ('software', 'Software'), ('automation', 'Automatización'), ('sales', 'Ventas'), ('productivity', 'Productividad')], max_length=30, verbose_name='Categoría')),
                ('metric', models.CharField(blank=True, max_length=50, verbose_name='Métrica principal (ej: −95%)')),
                ('metric_label', models.CharField(blank=True, max_length=100, verbose_name='Etiqueta de métrica')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caso de éxito',
                'verbose_name_plural': 'Casos de éxito',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessCaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cases/', verbose_name='Imagen')),
                ('image_type', models.CharField(choices=[('before', 'Antes'), ('after', 'Después'), ('general', 'General')], default='general', max_length=10, verbose_name='Tipo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cases.successcase', verbose_name='Caso')),
            ],
            options={
                'verbose_name': 'Imagen de caso',
                'verbose_name_plural': 'Imágenes de caso',
                'ordering': ['order'],
            },
        ),
    ]
