# Generated by Django 5.2.14 on 2026-05-09 01:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('level', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='basic', max_length=20, verbose_name='Nivel')),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hybrid', 'Híbrido')], default='online', max_length=20, verbose_name='Modalidad')),
                ('date', models.DateField(verbose_name='Fecha de inicio')),
                ('time_start', models.TimeField(verbose_name='Hora de inicio')),
                ('time_end', models.TimeField(verbose_name='Hora de fin')),
                ('duration', models.CharField(max_length=100, verbose_name='Duración')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (MXN)')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Cupo máximo')),
                ('location', models.CharField(max_length=300, verbose_name='Lugar')),
                ('instructor_name', models.CharField(blank=True, max_length=200, verbose_name='Nombre instructor (texto libre)')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('closed', 'Cerrado'), ('finished', 'Finalizado')], default='draft', max_length=20, verbose_name='Estado')),
                ('accent', models.CharField(choices=[('cyan', 'Cyan'), ('magenta', 'Magenta'), ('violet', 'Violet')], default='cyan', max_length=20, verbose_name='Color acento')),
                ('short_description', models.CharField(max_length=500, verbose_name='Descripción corta')),
                ('description', models.TextField(verbose_name='Descripción completa')),
                ('benefits', models.JSONField(default=list, verbose_name='Beneficios')),
                ('curriculum', models.JSONField(default=list, verbose_name='Temario')),
                ('requirements', models.JSONField(default=list, verbose_name='Requisitos')),
                ('target_audience', models.CharField(blank=True, max_length=300, verbose_name='Público objetivo')),
                ('promo_video_url', models.URLField(blank=True, verbose_name='Video promocional URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.category', verbose_name='Categoría')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='workshops.instructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Taller',
                'verbose_name_plural': 'Talleres',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Orden (0-4)')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Imagen de taller',
                'verbose_name_plural': 'Imágenes de taller',
                'ordering': ['order'],
            },
        ),
    ]
